### ISSUE TITLE
marshmallow-to-swagger fail for self-referential nested fields 

### ISSUE THREAD

**Issue by ahayschi** [plangrid/flask-rebar#90] opened 2019-05-06 16:19 UTC
Version: 1.5.1

It does not look like there is support for marshmallow [self-referential nested fields](https://marshmallow.readthedocs.io/en/2.x-line/nesting.html#nesting-a-schema-within-itself) in the swagger generation.

Schema:
```python
class FooSchema(Schema):
    field1 = fields.Nested('self', exclude=('field1',), many=True, dump_only=True)
```

Error:
```
File ". . . flask_rebar/swagger_generation/marshmallow_to_swagger.py", line 312, in convert
    inst = nested_obj()
TypeError: 'str' object is not callable
```

It appears that the NestedConverter is trying to instantiate the field and doesn't handle a self reference:
```python
# instantiate the object because the converter expects it to be
        inst = nested_obj()
```

**Comment by twosigmajab** [comment] 2019-05-11 21:55
FWIW other Flask-Rebar users I'm supporting have been hitting this too. I'll take a look next chance I get if no one beats me to it.

**Comment by RookieRick** [comment] 2019-05-13 15:23
> FWIW other Flask-Rebar users I'm supporting have been hitting this too. I'll take a look next chance I get if no one beats me to it.

Thanks!  Whoever starts working on this one drop a quick note here and/or better yet be sure to self-assign the issue so everybody else knows to keep their fingers and toes out of the way.  I would like to say I'll try to work on this one this week but I also should be realistic and acknowledge that this week is gonna be crazy for me :)

**Comment by barakalon** [comment] 2019-05-15 18:28
I also think flask-rebar doesn't yet support `exclude` nor `only` (https://marshmallow.readthedocs.io/en/3.0/quickstart.html#filtering-output), which we'll need for this.

**Comment by askeladdk** [comment] 2019-09-17 13:06
I'm having the same problem and after a lot of digging I figured it out. The problem is that `obj.nested` is a string when the first argument of `fields.Nested` is a string instead of a schema object. It turns out that `obj.schema` contains the resolved schema object. So until this has been fixed in the library you can use this temporary fix:
```
from flask_rebar.swagger_generation.marshmallow_to_swagger import NestedConverter, request_body_converter_registry, response_converter_registry

class MyNestedConverter(NestedConverter):
    def convert(self, obj, context):
        inst = obj.schema # <-- here is the fix
        if obj.many:
            return {sw.type_: sw.array, sw.items: context.convert(inst, context)}
        else:
            return context.convert(inst, context)

# Register our converter with the default converter registries.
request_body_converter_registry.register_type(MyNestedConverter())
response_converter_registry.register_type(MyNestedConverter())
```

**Comment by RookieRick** [comment] 2020-08-11 18:27
Tagging this one as "v2.0" as it seems like it's likely to be increasingly prevalent once we've moved to marshmallow 3 with support for `exclude` and `only`

**Comment by PratikPramanik** [comment] 2021-01-26 20:05
Noticed this difference between the obj.schema and obj.nested() @RookieRick 
![image](https://user-images.githubusercontent.com/549526/105898809-bcc71f00-5fce-11eb-8f81-f0c545f4699a.png)

**Comment by RookieRick** [comment] 2021-06-29 23:32
Pleased to announce the legwork everybody else has done here has led me to a delightful "AHA" moment.  I'm doing some sanity checking before I push more commits to the associated PR but so far it would appear that:
1. We can just make our `NestedConverter` really dumb (**_all_** it has to do is call `convert` on  `obj.schema` 😂 )
2. Doing it that way gets us `exclude` and `only` for free 🎉

**Closed** 2021-06-30 00:09 UTC
Labels: bug, swagger-generation, triaged, v2-breaking-change, v2.0
